language: c

compiler:
  - gcc

install:
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo apt-get update -qq
 - sudo apt-get install gcc-arm-none-eabi -y
 - pushd firmware
 - mkdir -p bin

script:
 - make TARGET=STM32
